# Para compilar es necesaro el bundle de arduino (1.0.5)
# 1.5 Beta -> no compatible con CATERINA !!!
##
ARDUINO_DIR =/usr/local/Cellar/arduino/1.0.5

BOARD_TAG	= esplora
MONITOR_PORT=/dev/tty.usb*
ISP_PORT	=/dev/tty.usb*

ARDUINO_CORE_PATH	=core/arduino

### path to Arduino.mk, inside the ARDMK_DIR, don't touch.
include core/Arduino.mk